# Introduction to Data Manipulation in Python - Part 2  
**Course**: HUDK 4050, Week 4  
**Author**: Zecheng Chang  
**Assignment**: ICE2  
**Objectives**:
1. Index Data
2. Create data mask for filtering. 
3. Combine datasets
4. Aggregate, group data as well as create pivot tables

### Data Manipulation in `array`

In [1]:
import numpy as np # Don't forget to import numpy

np.random.seed(123) 
m1 = np.random.randint(0, 100, size = 10) # Create a array of 10 random integers in the interval [0, 100)
m2 = np.random.randint(10, size=(3, 4)) # Create a 3 x 4 array of in the interval [0, 10)
print("The one-dimensional array looks like this:\n", m1)
print("The two-dimensional array looks like this:\n", m2)

The one-dimensional array looks like this:
 [66 92 98 17 83 57 86 97 96 47]
The two-dimensional array looks like this:
 [[9 0 0 9]
 [3 4 0 0]
 [4 1 7 3]]


### Accessing single elements

In [5]:
m1

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [3]:
m1[0]

66

In [4]:
m1[-2]

96

In [6]:
m2[0,-1]

9

### Accessing subarrays

In [7]:
m1

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [13]:
m1[1:7:2]

array([92, 17, 57])

In [14]:
m1[:5]

array([66, 92, 98, 17, 83])

In [15]:
m1[5:]

array([57, 86, 97, 96, 47])

In [16]:
m1[::2]

array([66, 98, 83, 86, 96])

In [18]:
#access every other element starting from the second?
m1[1::2]

array([92, 17, 57, 97, 47])

### Multi-dimension manipulation

In [19]:
m2[:2,:3]

array([[9, 0, 0],
       [3, 4, 0]])

In [20]:
m2[:,0]

array([9, 3, 4])

In [21]:
m2[0,:]

array([9, 0, 0, 9])

In [22]:
m2[m2 > 1]

array([9, 9, 3, 4, 4, 7, 3])

### Usefull tricks for `array`

In [27]:
grid = np.array([[1,2,3],
                 [4,5,6]])

np.concatenate([grid,grid+1],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [5, 6, 7]])

In [25]:
np.vstack([grid,grid+1])

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [5, 6, 7]])

In [28]:
np.hstack([grid, grid+1])

array([[1, 2, 3, 2, 3, 4],
       [4, 5, 6, 5, 6, 7]])

In [34]:
m2.reshape((4,3))

array([[9, 0, 0],
       [9, 3, 4],
       [0, 0, 4],
       [1, 7, 3]])

### Data indexing in series

In [36]:
import pandas as pd

s1 = pd.Series([0.25,0.5,0.75,1.0],
              index=['a','b','c','d'])

s1

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [37]:
s1['b']

0.5

In [38]:
s1[1]

0.5

In [39]:
s1['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [40]:
s1[0:2]

a    0.25
b    0.50
dtype: float64

In [41]:
s1[(s1 > 0.3) & (s1 < 0.8)]

b    0.50
c    0.75
dtype: float64

In [42]:
s2 = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
s2

1    a
3    b
5    c
dtype: object

In [43]:
s2[1]

'a'

In [46]:
s2

1    a
3    b
5    c
dtype: object

In [49]:
s2[1:3]

3    b
5    c
dtype: object

In [60]:
s2.iloc[0:3]

1    a
3    b
5    c
dtype: object

### Data indexing in DataFrame¶

In [62]:
ICEdata = pd.read_csv("ICE1_Data.csv")

ICEdata

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
0    01M292           Developing                  C                      C   
1    01M448           Developing                  C                      B   
2    01M450       Well Developed                  A                      B   
3    01M509           Proficient                  C                      C   
4    01M539           Proficient                  A                      A   
..      ...                  ...                ...                    ...   
417  10X696       Well Developed                  A                      A   
418  13K430           Proficient                  B                      B   
419  10X445       Well Developed                  A                      A   
420  14K449       Well Developed                  B                      B   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  
0                 0.563                   0.519  
1                 0.707                   0.363  
2                 0.716                   0.692  
3                 0.564                   0.477  
4                 0.953                   0.870  
..                  ...                     ...  
417               1.000                   0.936  
418               0.977                   0.867  
419               1.000                   0.994  
420               0.914                   0.961  
421               1.000                   0.972  

[422 rows x 6 columns]

In [64]:
ICEdata['Quality_Review_Score']

0          Developing
1          Developing
2      Well Developed
3          Proficient
4          Proficient
            ...      
417    Well Developed
418        Proficient
419    Well Developed
420    Well Developed
421        Proficient
Name: Quality_Review_Score, Length: 422, dtype: object

In [65]:
ICEdata['collegeRate'] = ICEdata['college enroll 2010-11'] / ICEdata['graduation 2010-11']
ICEdata

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
0    01M292           Developing                  C                      C   
1    01M448           Developing                  C                      B   
2    01M450       Well Developed                  A                      B   
3    01M509           Proficient                  C                      C   
4    01M539           Proficient                  A                      A   
..      ...                  ...                ...                    ...   
417  10X696       Well Developed                  A                      A   
418  13K430           Proficient                  B                      B   
419  10X445       Well Developed                  A                      A   
420  14K449       Well Developed                  B                      B   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  collegeRate  
0                 0.563                   0.519     0.921847  
1                 0.707                   0.363     0.513437  
2                 0.716                   0.692     0.966480  
3                 0.564                   0.477     0.845745  
4                 0.953                   0.870     0.912907  
..                  ...                     ...          ...  
417               1.000                   0.936     0.936000  
418               0.977                   0.867     0.887410  
419               1.000                   0.994     0.994000  
420               0.914                   0.961     1.051422  
421               1.000                   0.972     0.972000  

[422 rows x 7 columns]

In [66]:
ICEdata.loc[0]

DBN                           01M292
Quality_Review_Score      Developing
Progress_Rpt_10-11                 C
Student_Progress_10-11             C
graduation 2010-11             0.563
college enroll 2010-11         0.519
collegeRate                 0.921847
Name: 0, dtype: object

In [67]:
ICEdata.iloc[:3,:2]

DBN Quality_Review_Score
0  01M292           Developing
1  01M448           Developing
2  01M450       Well Developed

In [68]:
ICEdata.loc[:20, :'Progress_Rpt_10-11']


DBN Quality_Review_Score Progress_Rpt_10-11
0   01M292           Developing                  C
1   01M448           Developing                  C
2   01M450       Well Developed                  A
3   01M509           Proficient                  C
4   01M539           Proficient                  A
5   01M696       Well Developed                  B
6   02M047           Proficient                  C
7   02M288           Proficient                  A
8   02M294       Well Developed                  B
9   02M296           Proficient                  A
10  02M298       Well Developed                  A
11  02M300           Proficient                  B
12  02M303           Proficient                  B
13  02M305           Proficient                  C
14  02M308       Well Developed                  A
15  02M316           Proficient                  B
16  02M374           Proficient                  C
17  02M376       Well Developed                NaN
18  02M392           Proficient                NaN
19  02M393           Proficient                NaN
20  02M399           Proficient                NaN

In [69]:
ICEdata[ICEdata['graduation 2010-11'] > 0.75]

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
4    01M539           Proficient                  A                      A   
5    01M696       Well Developed                  B                      C   
7    02M288           Proficient                  A                      B   
9    02M296           Proficient                  A                      A   
10   02M298       Well Developed                  A                      A   
..      ...                  ...                ...                    ...   
417  10X696       Well Developed                  A                      A   
418  13K430           Proficient                  B                      B   
419  10X445       Well Developed                  A                      A   
420  14K449       Well Developed                  B                      B   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  collegeRate  
4                 0.953                   0.870     0.912907  
5                 0.976                   0.957     0.980533  
7                 0.820                   0.627     0.764634  
9                 0.793                   0.560     0.706179  
10                0.915                   0.796     0.869945  
..                  ...                     ...          ...  
417               1.000                   0.936     0.936000  
418               0.977                   0.867     0.887410  
419               1.000                   0.994     0.994000  
420               0.914                   0.961     1.051422  
421               1.000                   0.972     0.972000  

[135 rows x 7 columns]

### Data  Masking

In [72]:
m2

array([[9, 0, 0, 9],
       [3, 4, 0, 0],
       [4, 1, 7, 3]])

In [73]:
m2 < 2

array([[False,  True,  True, False],
       [False, False,  True,  True],
       [False,  True, False, False]])

In [74]:
m2[m2<2]

array([0, 0, 0, 0, 1])

In [75]:
mask = (m2>2) & (m2<5)

In [78]:
m2[mask]

array([3, 4, 4, 3])

In [79]:
ICEmask = (ICEdata['graduation 2010-11'] > 0.75) & (ICEdata['Progress_Rpt_10-11'] == 'A') & (ICEdata['Student_Progress_10-11'] == 'B')
ICEdata[ICEmask]


DBN                    Quality_Review_Score Progress_Rpt_10-11  \
7    02M288                              Proficient                  A   
25   02M412                              Proficient                  A   
75   04M435                          Well Developed                  A   
78   04M610                              Proficient                  A   
85   05M670                              Developing                  A   
107  07X548                              Proficient                  A   
108  07X551                              Proficient                  A   
147  09X543                          Well Developed                  A   
149  10X141                              Proficient                  A   
158  10X374                          Well Developed                  A   
161  10X437                              Developing                  A   
175  11X275                              Proficient                  A   
206  13K419                              Proficient                  A   
220  14K478                          Well Developed                  A   
251  17K531                              Proficient                  A   
274  19K404                          Well Developed                  A   
305  22K535                          Well Developed                  A   
308  23K514                              Proficient                  A   
334  26Q430                              Proficient                  A   
336  26Q495                          Well Developed                  A   
356  28Q440                              Proficient                  A   
357  28Q505                              Proficient                  A   
358  28Q620                          Well Developed                  A   
383  31R080                              Proficient                  A   
384  31R440                          Well Developed                  A   
413  03M485  Outstanding (only an option in 2007-8)                  A   
415  02M475                          Well Developed                  A   
416  05M692                          Well Developed                  A   
421  28Q687                              Proficient                  A   

    Student_Progress_10-11  graduation 2010-11  college enroll 2010-11  \
7                        B               0.820                   0.627   
25                       B               0.964                   0.774   
75                       B               0.920                   0.757   
78                       B               0.984                   0.982   
85                       B               0.789                   0.559   
107                      B               0.866                   0.663   
108                      B               0.831                   0.605   
147                      B               0.765                   0.319   
149                      B               0.870                   0.784   
158                      B               0.939                     NaN   
161                      B               0.855                   0.325   
175                      B               0.762                   0.517   
206                      B               0.802                   0.399   
220                      B               0.847                   0.432   
251                      B               0.787                   0.433   
274                      B               0.855                   0.538   
305                      B               0.958                   0.862   
308                      B               0.769                   0.467   
334                      B               0.875                   0.680   
336                      B               0.862                   0.745   
356                      B               0.844                   0.649   
357                      B               0.756                   0.529   
358                      B               0.877                   0.697   
383        

### Combining datasets

In [80]:
def make_df(cols, ind):
    #Quickly make a DataFrame
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# example DataFrame
make_df('ABC', range(3))


A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [81]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1, "\n\n\n")
print(df2, "\n\n\n")
print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2 



    A   B
3  A3  B3
4  A4  B4 



    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [82]:
df3 = make_df('ABC', [1, 2])
df4 = make_df('BCD', [3, 4])
print(df3, "\n\n\n")
print(df4, "\n\n\n")
print(pd.concat([df3, df4]))


    A   B   C
1  A1  B1  C1
2  A2  B2  C2 



    B   C   D
3  B3  C3  D3
4  B4  C4  D4 



     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


/Users/czc/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """


In [83]:
pd.concat([df3,df4], join = 'inner')

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [84]:
df5 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df6 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
dfm = pd.merge(df5, df6)

print(df5, "\n\n\n")
print(df6, "\n\n\n")
print(dfm)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR 



  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014 



  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


In [85]:
df7 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})

dfm = pd.merge(df5, df7)
print(df7, "\n\n\n")

print(dfm)

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve 



  employee        group supervisor
0      Bob   Accounting      Carly
1     Jake  Engineering      Guido
2     Lisa  Engineering      Guido
3      Sue           HR      Steve


In [86]:
pd.merge(df5, df6, on='employee')


employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [87]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
pd.merge(df5, df8, left_on = 'employee', right_on = 'name')

employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

### Aggregation, grouping, and pivot tables¶

In [88]:
ICEdata.describe(include = 'all')

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
count      422                  368                310                    310   
unique     422                    6                  5                      5   
top     28Q686           Proficient                  A                      C   
freq         1                  186                109                     93   
mean       NaN                  NaN                NaN                    NaN   
std        NaN                  NaN                NaN                    NaN   
min        NaN                  NaN                NaN                    NaN   
25%        NaN                  NaN                NaN                    NaN   
50%        NaN                  NaN                NaN                    NaN   
75%        NaN                  NaN                NaN                    NaN   
max        NaN                  NaN                NaN                    NaN   

        graduation 2010-11  college enroll 2010-11  collegeRate  
count           310.000000              291.000000   291.000000  
unique                 NaN                     NaN          NaN  
top                    NaN                     NaN          NaN  
freq                   NaN                     NaN          NaN  
mean              0.737977                0.531196     0.707836  
std               0.143356                0.193129     0.168986  
min               0.412000                0.141000     0.262570  
25%               0.625250                0.391000     0.589317  
50%               0.726000                0.489000     0.707569  
75%               0.850750                0.656000     0.838918  
max               1.000000                1.000000     1.101227

In [90]:
ICEdata.mean()

graduation 2010-11        0.737977
college enroll 2010-11    0.531196
collegeRate               0.707836
dtype: float64

In [91]:
ICEdata['graduation 2010-11'].max()

1.0

In [93]:
ICEdata.groupby('Quality_Review_Score').mean()

graduation 2010-11  \
Quality_Review_Score                                                     
Developing                                                    0.633019   
Outstanding (only an option in 2007-8)                        0.864333   
Proficient                                                    0.729554   
Underdeveloped                                                0.549667   
Underdeveloped with Proficient Features (only a...                 NaN   
Well Developed                                                0.823367   

                                                    college enroll 2010-11  \
Quality_Review_Score                                                         
Developing                                                        0.402830   
Outstanding (only an option in 2007-8)                            0.747667   
Proficient                                                        0.521208   
Underdeveloped                                                    0.350167   
Underdeveloped with Proficient Features (only a...                     NaN   
Well Developed                                                    0.625871   

                                                    collegeRate  
Quality_Review_Score                                             
Developing                                             0.641309  
Outstanding (only an option in 2007-8)                 0.864183  
Proficient                                             0.703604  
Underdeveloped                                         0.631451  
Underdeveloped with Proficient Features (only a...          NaN  
Well Developed                                         0.752696

In [94]:
ICEdata.groupby('Quality_Review_Score')['graduation 2010-11'].describe()

count      mean       std  \
Quality_Review_Score                                                            
Developing                                           53.0  0.633019  0.107199   
Outstanding (only an option in 2007-8)                3.0  0.864333  0.102051   
Proficient                                          157.0  0.729554  0.135946   
Underdeveloped                                        6.0  0.549667  0.061805   
Underdeveloped with Proficient Features (only a...    0.0       NaN       NaN   
Well Developed                                       90.0  0.823367  0.121570   

                                                      min      25%    50%  \
Quality_Review_Score                                                        
Developing                                          0.457  0.56300  0.615   
Outstanding (only an option in 2007-8)              0.800  0.80550  0.811   
Proficient                                          0.412  0.63000  0.722   
Underdeveloped                                      0.457  0.51525  0.554   
Underdeveloped with Proficient Features (only a...    NaN      NaN    NaN   
Well Developed                                      0.545  0.72775  0.833   

                                                        75%    max  
Quality_Review_Score                                                
Developing                                          0.69800  0.947  
Outstanding (only an option in 2007-8)              0.89650  0.982  
Proficient                                          0.81100  1.000  
Underdeveloped                                      0.59350  0.624  
Underdeveloped with Proficient Features (only a...      NaN    NaN  
Well Developed                                      0.91875  1.000

In [95]:
ICEdata.groupby(['Quality_Review_Score', 'Progress_Rpt_10-11']).count().unstack()

DBN                         \
Progress_Rpt_10-11                         A     B     C     D    F   
Quality_Review_Score                                                  
Developing                               4.0  11.0  19.0  16.0  3.0   
Outstanding (only an option in 2007-8)   3.0   NaN   NaN   NaN  NaN   
Proficient                              48.0  65.0  39.0   5.0  NaN   
Underdeveloped                           NaN   NaN   3.0   1.0  2.0   
Well Developed                          53.0  26.0  11.0   NaN  NaN   

                                       Student_Progress_10-11              \
Progress_Rpt_10-11                                          A     B     C   
Quality_Review_Score                                                        
Developing                                                4.0  11.0  19.0   
Outstanding (only an option in 2007-8)                    3.0   NaN   NaN   
Proficient                                               48.0  65.0  39.0   
Underdeveloped                                            NaN   NaN   3.0   
Well Developed                                           53.0  26.0  11.0   

                                                   ... college enroll 2010-11  \
Progress_Rpt_10-11                         D    F  ...                      A   
Quality_Review_Score                               ...                          
Developing                              16.0  3.0  ...                    3.0   
Outstanding (only an option in 2007-8)   NaN  NaN  ...                    3.0   
Proficient                               5.0  NaN  ...                   45.0   
Underdeveloped                           1.0  2.0  ...                    NaN   
Well Developed                           NaN  NaN  ...                   48.0   

                                                              collegeRate  \
Progress_Rpt_10-11                         B     C     D    F           A   
Quality_Review_Score                                                        
Developing                              11.0  16.0  15.0  2.0         3.0   
Outstanding (only an option in 2007-8)   NaN   NaN   NaN  NaN         3.0   
Proficient                              63.0  37.0   4.0  NaN        45.0   
Underdeveloped                           NaN   3.0   1.0  2.0         NaN   
Well Developed                          26.0  11.0   NaN  NaN        48.0   

                                                               
Progress_Rpt_10-11                         B     C     D    F  
Quality_Review_Score                                           
Developing                              11.0  16.0  15.0  2.0  
Outstanding (only an option in 2007-8)   NaN   NaN   NaN  NaN  
Proficient                              63.0  37.0   4.0  NaN  
Underdeveloped                           NaN   3.0   1.0  2.0  
Well Developed                          26.0  11.0   NaN  NaN  

[5 rows x 25 columns]

In [96]:
ICEdata.groupby('Quality_Review_Score').aggregate(['median', 'min', 'max'])

graduation 2010-11         \
                                                               median    min   
Quality_Review_Score                                                           
Developing                                                      0.615  0.457   
Outstanding (only an option in 2007-8)                          0.811  0.800   
Proficient                                                      0.722  0.412   
Underdeveloped                                                  0.554  0.457   
Underdeveloped with Proficient Features (only a...                NaN    NaN   
Well Developed                                                  0.833  0.545   

                                                           \
                                                      max   
Quality_Review_Score                                        
Developing                                          0.947   
Outstanding (only an option in 2007-8)              0.982   
Proficient                                          1.000   
Underdeveloped                                      0.624   
Underdeveloped with Proficient Features (only a...    NaN   
Well Developed                                      1.000   

                                                   college enroll 2010-11  \
                                                                   median   
Quality_Review_Score                                                        
Developing                                                         0.4030   
Outstanding (only an option in 2007-8)                             0.6920   
Proficient                                                         0.4900   
Underdeveloped                                                     0.3715   
Underdeveloped with Proficient Features (only a...                    NaN   
Well Developed                                                     0.5920   

                                                                 collegeRate  \
                                                      min    max      median   
Quality_Review_Score                                                           
Developing                                          0.165  0.658    0.647416   
Outstanding (only an option in 2007-8)              0.690  0.861    0.862500   
Proficient                                          0.183  0.990    0.699735   
Underdeveloped                                      0.141  0.465    0.712859   
Underdeveloped with Proficient Features (only a...    NaN    NaN         NaN   
Well Developed                                      0.268  1.000    0.765269   

                                                                        
                                                         min       max  
Quality_Review_Score                                                    
Developing                                          0.271829  1.048622  
Outstanding (only an option in 2007-8)              0.853268  0.876782  
Proficient                                          0.296503  1.101227  
Underdeveloped                                      0.262570  0.756567  
Underdeveloped with Proficient Features (only a...       NaN       NaN  
Well Developed                                      0.388970  1.051422

In [97]:
ICEdata.groupby(['Quality_Review_Score', 'Progress_Rpt_10-11'])['graduation 2010-11'].aggregate('mean').unstack()

Progress_Rpt_10-11                             A         B         C  \
Quality_Review_Score                                                   
Developing                              0.716500  0.654545  0.639474   
Outstanding (only an option in 2007-8)  0.864333       NaN       NaN   
Proficient                              0.817083  0.722077  0.660333   
Underdeveloped                               NaN       NaN  0.556333   
Well Developed                          0.862472  0.791000  0.711455   

Progress_Rpt_10-11                             D         F  
Quality_Review_Score                                        
Developing                              0.613812  0.504333  
Outstanding (only an option in 2007-8)       NaN       NaN  
Proficient                              0.526400       NaN  
Underdeveloped                          0.457000  0.586000  
Well Developed                               NaN       NaN

In [98]:
ICEdata.pivot_table('graduation 2010-11', index='Quality_Review_Score', columns='Progress_Rpt_10-11')

Progress_Rpt_10-11                             A         B         C  \
Quality_Review_Score                                                   
Developing                              0.716500  0.654545  0.639474   
Outstanding (only an option in 2007-8)  0.864333       NaN       NaN   
Proficient                              0.817083  0.722077  0.660333   
Underdeveloped                               NaN       NaN  0.556333   
Well Developed                          0.862472  0.791000  0.711455   

Progress_Rpt_10-11                             D         F  
Quality_Review_Score                                        
Developing                              0.613812  0.504333  
Outstanding (only an option in 2007-8)       NaN       NaN  
Proficient                              0.526400       NaN  
Underdeveloped                          0.457000  0.586000  
Well Developed                               NaN       NaN

In [101]:
ICEdata.pivot_table(index='Quality_Review_Score', columns='Progress_Rpt_10-11')

college enroll 2010-11            \
Progress_Rpt_10-11                                          A         B   
Quality_Review_Score                                                      
Developing                                           0.349667  0.441000   
Outstanding (only an option in 2007-8)               0.747667       NaN   
Proficient                                           0.599622  0.494762   
Underdeveloped                                            NaN       NaN   
Well Developed                                       0.658937  0.621115   

                                                                    \
Progress_Rpt_10-11                             C         D       F   
Quality_Review_Score                                                 
Developing                              0.395063  0.406467  0.3075   
Outstanding (only an option in 2007-8)       NaN       NaN     NaN   
Proficient                              0.475784  0.475750     NaN   
Underdeveloped                          0.303333  0.311000  0.4400   
Well Developed                          0.492818       NaN     NaN   

                                       collegeRate                      \
Progress_Rpt_10-11                               A         B         C   
Quality_Review_Score                                                     
Developing                                0.453479  0.664102  0.648968   
Outstanding (only an option in 2007-8)    0.864183       NaN       NaN   
Proficient                                0.717625  0.676312  0.716647   
Underdeveloped                                 NaN       NaN  0.535396   
Well Developed                            0.756130  0.774449  0.686298   

                                                           graduation 2010-11  \
Progress_Rpt_10-11                             D         F                  A   
Quality_Review_Score                                                            
Developing                              0.655688  0.628580           0.716500   
Outstanding (only an option in 2007-8)       NaN       NaN           0.864333   
Proficient                              0.855056       NaN           0.817083   
Underdeveloped                          0.680525  0.750996                NaN   
Well Developed                               NaN       NaN           0.862472   

                                                                                
Progress_Rpt_10-11                             B         C         D         F  
Quality_Review_Score                                                            
Developing                              0.654545  0.639474  0.613812  0.504333  
Outstanding (only an option in 2007-8)       NaN       NaN       NaN       NaN  
Proficient                              0.722077  0.660333  0.526400       NaN  
Underdeveloped                               NaN  0.556333  0.457000  0.586000  
Well Developed                          0.791000  0.711455       NaN       NaN

In [102]:
ICEdata.pivot_table('graduation 2010-11',
                    index='Quality_Review_Score',
                    columns='Progress_Rpt_10-11',
                   aggfunc = 'median')

Progress_Rpt_10-11                          A       B      C      D      F
Quality_Review_Score                                                      
Developing                              0.702  0.6290  0.587  0.615  0.506
Outstanding (only an option in 2007-8)  0.811     NaN    NaN    NaN    NaN
Proficient                              0.806  0.7150  0.662  0.531    NaN
Underdeveloped                            NaN     NaN  0.537  0.457  0.586
Well Developed                          0.879  0.8145  0.676    NaN    NaN